spring:
#  Gatewat Configs to map request coming in frm port 8080 to respective microservice's port
#  This way, the url of each microservice is hidden/abstracted from external apps
#  Only the api gateway is exposed, while the internal microservices are hidden
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE-APPLICATION
          predicates:
            - Path=/api/users/**
        - id: activity-service
          uri: lb://ACTIVITY-SERVICE-APPLICATION
          predicates:
            - Path=/api/activities/**
        - id: ai-service
          uri: lb://AI-SERVICE-APPLICATION
          predicates:
            - Path=/api/recommendations/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
